name: Verification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install texlive texlive-xetex pandoc librsvg2-bin

      - name: Render documentation
        run: make

      - uses: actions/upload-artifact@v2
        with:
          name: Specification
          path: |
            specification.pdf
            specification.md
            specification.txt
